name:  dnsvalidator Dockerbuild

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  id-token: write
  packages: write

concurrency:
  group: "image-push"

env:
  TARGET_REGISTRY: "ghcr.io/${{ github.repository }}"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.TARGET_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.TARGET_REGISTRY }}:latest
          cache-from: type=registry,ref=${{ env.TARGET_REGISTRY }}:${{ github.sha }}
          cache-to: type=inline,mode=max
